#!/usr/bin/env bash
# Script that configures a brand new Ubuntu machine as load balancer
sudo apt-get update
sudo apt-get -y install haproxy
echo "frontend HAproxyfront
        bind *:80
        mode http
        default_backend HAproxyback
backend HAproxyback
        mode http
        server web-01 52.3.255.212 
        server web-02 100.24.235.178" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
