#!/usr/bin/env bash
# Script to transfer file to server
if [ "$#" -ne 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
file="$1"
ip="$2"
username="$3"
path_to_ssh="$4"
scp -o StrictHostKeyChecking=no -i "$path_to_ssh" "$file" "$username@$ip":~
