#!/usr/bin/env bash
# Shell script for if file is existing and if empty
if [ -e "school" ]
then
	echo "school file exists"
	if [ -s "school" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exist"
fi

if [ -f "school" ]
then
	echo "school file is a regular file"
fi
