#!/usr/bin/env bash
# Bash script to run nginx on nginx user + listen to 8080

# Change User to nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# Nginx listens to 8080 instead of 80
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# Change permissions
chmod 644 /etc/nginx/nginx.conf
pkill apache2
# Restart Nginx
sudo -u nginx service nginx start
