#!/usr/bin/env bash
# Bash script to run nginx on nginx user + listen to 8080

# Change User
sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
# Change Port
sed -i "s/80/8080/g" /etc/nginx/sites-available/dafault
chmod 644 /etc/nginx/nginx.conf
pkill apache2
# Nginx restart
sudo -u nginx service nginx start
